import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { RainbowProvider } from "@/components/RainbowProvider";
import "@rainbow-me/rainbowkit/styles.css";
import Navbar from "@/components/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <RainbowProvider>
          <Navbar />
          {children}
        </RainbowProvider>
      </body>
    </html>
  );
}
